title: 'Graficación y Animación'
default_lang: en
author:
  name: 'Denis Cabeza'
  email: deniskabeza@gmail.com
taxonomies:
  - category
  - tag
  - cms
  - flatfile
metadata:
  description: 'Blog creado con tecnología flat-file CMS para la materia graficación y animación.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
email: deniskabeza@gmail.com
description: 'Blog creado con tecnología flat-file CMS para la materia graficación y animación.'
links:
  -
    title: Servicios
    url: '#services'
  -
    title: Portafolio
    url: '#portfolio'
  -
    title: Trayectoria
    url: '#about'
  -
    title: 'Sobre Mi'
    url: '#team'
  -
    title: Contacto
    url: '#contact'
social:
  -
    title: twitter
    url: 'http://www.twitter.com/deniscabezav'
  -
    title: facebook
    url: 'http://www.facebook.com/deniscabezav'
  -
    title: stack-overflow
    url: 'http://stackoverflow.com/questions/tagged/jekyll'
  -
    title: bitbucket
    url: 'http://bitbucket.org/deniskabezav'
  -
    title: github
    url: 'http://github.com/deniscabezav'
address:
  -
    line: '15 de marzo'
  -
    line: 'Esmeraldas - Ecuador'
quicklinks:
  -
    title: 'Privacy Policy'
    url: '#'
  -
    title: 'Terms of Use'
    url: '#'
