title: 'Graficación y Animación'
default_lang: es
author:
  name: 'Denis Cabeza'
  email: deniskabeza@gmail.com
taxonomies:
  - tag
metadata:
  description: 'Grav is a flat-file CMS'
summary:
  enabled: true
  format: short
  size: 100
  delimiter: '==='
blog:
  route: /blog
description: 'Html - Css - Js - Docker - Git'
owner:
  name: 'Alex Kbza'
  email: alexkbzav@gmail.com
  description: 'Decide, Aprende y Emprende'
  twitter: alexkbzav
  facebook: alexkbzav
  github: null
  instagram: alexkbzav
  linkedin: alexkbzav
  google_plus: null
logo: /user/themes/notepad/images/logo.png
links:
  -
    title: 'Sobre Mi'
    url: /about
  -
    title: Contacto
    url: /contacto
include:
  - .htaccess
exclude:
  - lib
  - config.rb
  - Gemfile
  - Capfile
  - Gemfile.lock
  - config
  - log
  - Rakefile
  - Rakefile.rb
  - tmp
  - less
  - '*.sublime-project'
  - '*.sublime-workspace'
  - test
  - spec
  - Gruntfile.js
  - package.json
  - node_modules
