title: 'Graficación y Animación'
default_lang: es
author:
  name: 'Denis Cabeza'
  email: deniskabeza@gmail.com
taxonomies:
  - category
  - tag
  - cms
  - blog
metadata:
  description: 'Blog creado con el fin de mostrar los trabajos realizado en clases'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
email: deniskabeza@gmail.com
description: 'Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.'
links:
  -
    title: Servicios
    url: '#services'
  -
    title: Portafolio
    url: '#portfolio'
  -
    title: Trayectoria
    url: '#about'
  -
    title: 'Sobre Mi'
    url: '#team'
  -
    title: Contacto
    url: '#contact'
social:
  -
    title: twitter
    url: 'http://www.twitter.com/deniscabezav'
  -
    title: facebook
    url: 'https://www.facebook.com/DenisCabezaV'
  -
    title: stack-overflow
    url: null
  -
    title: bitbucket
    url: 'http://bitbucket.org/DenisCabezaV'
  -
    title: github
    url: 'http://github.com/DenisCabezaV'
address:
  -
    line: '15 de marzo'
  -
    line: 'Esmeraldas - Ecuador'
quicklinks:
  -
    title: 'Privacy Policy'
    url: '#'
  -
    title: 'Terms of Use'
    url: '#'
